export const FETCH_MOVIE_REQUESTING = 'FETCH_MOVIE_REQUESTING';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';
export const RESET_MOVIE = 'RESET_MOVIE';
